spring.application.name=match-be

# Active Profile
spring.profiles.active=mysql

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Server Configuration
server.port=8080

# JSON Configuration - Snake Case
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT-3

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Character Service Configuration
character.service.url=http://localhost:8081

# Logging
# logging.level.utn.frc.piv.parcial=DEBUG
# logging.level.org.springframework.security=DEBUG
